import { getHighlighter } from "@/lib/shiki";
import { CopyButton } from "./CopyButton";

interface CodeBlockProps {
  readonly code: string;
  readonly language: string;
  readonly filename?: string | undefined;
  readonly description?: string | undefined;
}

/**
 * Server-rendered syntax-highlighted code block using Shiki.
 * Zero client-side JavaScript for rendering.
 * CopyButton is the only client component.
 */
export async function CodeBlock({
  code,
  language,
  filename,
  description,
}: CodeBlockProps) {
  const hl = await getHighlighter();
  // Safe: code comes from our own TypeScript data files, never user input.
  const html = hl.codeToHtml(code.trim(), {
    lang: language,
    theme: "github-dark-dimmed",
  });

  return (
    <figure className="my-6 overflow-hidden rounded-xl border border-[#2a3040]">
      {/* Header bar */}
      <div className="flex items-center justify-between border-b border-[#2a3040] bg-[#1c2333] px-4 py-2.5">
        <div className="flex min-w-0 items-center gap-3">
          {/* Traffic lights */}
          <div className="flex shrink-0 gap-1.5" aria-hidden>
            <span className="h-2.5 w-2.5 rounded-full bg-[#3a3d41]" />
            <span className="h-2.5 w-2.5 rounded-full bg-[#3a3d41]" />
            <span className="h-2.5 w-2.5 rounded-full bg-[#3a3d41]" />
          </div>
          {filename && (
            <span className="truncate font-mono text-xs text-[#8899aa]">
              {filename}
            </span>
          )}
          {!filename && (
            <span className="font-mono text-xs text-[#4a5568]">{language}</span>
          )}
        </div>
        <CopyButton code={code} />
      </div>

      {/* Highlighted code */}
      <div
        className="overflow-x-auto [&>pre]:m-0 [&>pre]:rounded-none [&>pre]:bg-transparent [&>pre]:p-5 [&>pre]:text-sm [&>pre]:leading-7"
        // Safe: HTML generated by Shiki from our own code strings
        dangerouslySetInnerHTML={{ __html: html }}
      />

      {description && (
        <figcaption className="border-t border-[#2a3040] bg-[#1c2333] px-4 py-2 text-xs text-[#6e7f8f]">
          {description}
        </figcaption>
      )}
    </figure>
  );
}
